sshKeys:
    devoteam:
        private: ENC[AES256_GCM,data:F0VvtSzpyqQvZJBSVgbzyKSRlgolwMRgypZjuNFD26cucLP6CA2OI8xsCpyqTdAlzn844T9aB6RAuYlPbM2kryh0k8vhy8zWCcWsd/CuZNKiav+RuNt5F8yPvRIfbPPjSI3BXbq0TjVbU1I0kxzG5dXpykOTA7aVQ7/Jjvofosdg58pJNm4JGuJvfWpuRb0x1lL4jwmL1PRUQlw/kbgStBKc/zKpZQ/mxaekIOERwX7MGllqgt3PXtxtqht6h5opW9e7YX36e55sD5UXePC+WqmFAXtDpqq0EDK+hom5a7knsZnm/c3131nfcjE0tF1/7a8MIR1Gu1nn1ZErSM+YX793d1SrbkobZQUHWm0cm/ITkpGfWSo5FFirvX24TMAZGegDg1F4lquwvcdwUrIdVonXv+T25L65sPRCUJoj+tYcP0KObw3aoavI90shCG3kevb+FEG3uGlaEaaZxhlUFZsMBxyTNMjeaT9CqPlsxXYa/Pg50TTS9Wc01VgqlxRWATDShfNilUvHcMIgcAiV1hjdG2Iys6HNNEcsJwqebcTSsZXpcGDcscPvUMzoCdq58asdhUH6b2m/znHnQg2sLk+vLCpJWrYGpy9suDyKTTzzX8UOhCpcI+1FiVw1ezD9yCda,iv:aOKUcoYAnBzdmNMVtGT8MUhivQbMdzZ9H/L3poOyGRI=,tag:5JoIjdSccS7EiYZDQ8FIlg==,type:str]
        public: ENC[AES256_GCM,data:tTeHiLkGrS/9lAHmomxFlnf/yMvIGJH+zLygEgMte6qZVZW4IEn80RamImw2ILyWG2PwzOrJdy+nMEa1lLWpoRSkF9pw7kKLnWhorex6MNT2Kyt3NHO5SDfvV4rKziy2/ME5vbt31GgGchHsNN54uAh9IG4=,iv:0acd6iceIyn0RyuGEMK35NmnLhHcA+Zp66dBOD4K09c=,tag:USg5QVynfY3yhfL35fKxIQ==,type:str]
sops:
    age:
        - recipient: age1k2e5cle465gaw404avc69j7st02234g2wsueuccc4tk5gdhg4d3sgww8q3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTWduMlMyYzhwRFdPbkE1
            bmRDTVcyaG1ZVHpOOTFlbWx5WXlaUXh5N0VNCkxlWFdnc0VIR2FIWWJQNWR6YkVy
            VU0rdEVsaGFGdVhFK2k5RTNMODUrYlUKLS0tIEdpbVhPSTdkM04vQ1pOS3BmbWZM
            cWNuKzNWT1dkWDE5RWJ3Q2Rld2o5ZEkK3uY+Y5PFhDq9Yt8EVhICraOo7rCif05M
            NhyCXZizE7PrXf0dlhU9CeriInWEZixJm+EH+azWja7Zxqj6VwfoRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-14T00:49:32Z"
    mac: ENC[AES256_GCM,data:AE9MQCEhiuR8YoLFMDoVuAxEoUQmuzLr4sKJbUfkBU9guRHvExqMU53WGWZ3h9joc+Z+aZiU362NEo+dFbLAmxtqA/QjWTDEuJHf2lIfgLvu4LgBv0evQ8hyjtcUUK0fjDoCqTSQ0ZPZFyy06f+MRiMmrhW7wypqcZbkyC21Rzw=,iv:uaDuh9Epmhbhixj8O/GqSO2NTSQn8aGUIil3cNX2snw=,tag:+VarcYgFJTrew3p122m38Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
